module.exports = {
  PLATFORM_FEE_RATE:       parseFloat(process.env.PLATFORM_FEE_RATE) || 0.05,
  COOLDOWN_HOURS:          parseInt(process.env.COOLDOWN_HOURS) || 12,
  TRANSFER_CODE_PREFIX:    process.env.TRANSFER_CODE_PREFIX || 'BV',
  ENGLISH_DURATION_SECONDS: 120,
  ENGLISH_EXTEND_SECONDS:   30,
  ENGLISH_BREAK_SECONDS:    15,
  DEFAULT_REPUTATION_SCORE: 5.0,
  DEFAULT_PAGE_SIZE:        20,
};